services:
  backend:
    build: .
    image: yancotta/brim_invoice_streamlit_backend:latest
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/invoices"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  # Wait 30 seconds before starting healthchecks

  streamlit:
    build: .
    image: yancotta/brim_invoice_streamlit_streamlit:latest
    command: streamlit run frontend/app.py --server.port=8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy